baseURL = 'https://shiro.com/'
languageCode = 'en-us'
title = 'Shiro Makurokurosuke'
theme = "Shiro"

[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Tags"
    pre = "tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    name = "Products"
    pre = "products"
    url = "/products/"
    weight = 3