baseURL = 'https://shiro.com/'
languageCode = 'en-us'
title = 'Genshin Hugo'
theme = "Shiro"

[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Tags"
    pre = "tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    name = "Characters"
    pre = "characters"
    url = "/characters/"
    weight = 3